Implement profiles
s-things/wick pull request #113
Opened 2022-10-17 10:55 UTC by muzzammilshahid

### Description, Motivation and Context
It is expected that this PR is in a branch with a JIRA PLT-328 which thoroughly describes the change.

### What kind of change does this PR introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [ ] This changes or adds a WAMP RPC/PubSub
    - [ ] I have updated the WAMP API Catalogue in Notion and/or added the new schema to the st-schemas repo
- [ ] This changes logic or functionality
    - [ ] I have updated the README.md in this repo.

2022-10-19 08:23 UTC, bboozzoo commented on cmd/wick/helpers.go
> +	signal.Notify(sigCh, os.Interrupt)
why do you need signal handling here? if the user interrupts when reading the input it's fine to just exit which is the default behavior

2022-10-19 08:23 UTC, bboozzoo commented on cmd/wick/helpers.go
> +		if err = os.MkdirAll(filepath.Dir(filePath), os.ModePerm); err != nil {
os.ModePerm is a mask for obtaining the permission bits from stat's file mode info. So in this case, the code creates a directory with permissions 0777 (read & write by all) which is wrong.

```suggestion
		if err = os.MkdirAll(filepath.Dir(filePath), 0755); err != nil {
```

2022-10-19 08:23 UTC, bboozzoo commented on cmd/wick/helpers.go
> +	err := ensureFile(filePath)
do you need to create a file upfront? won't this work:
```
	cfg, err := ini.Load(filePath)
	if err != nil {
		if !os.IsNotExist(err) {
			return fmt.Errorf("fail to load config: %w", err)
		}
		// no config, use an empty one
		cfg = ini.Empty()
	}
```

and then writing:
```
	if err = os.MkdirAll(filepath.Dir(filePath), 0755); err != nil {
		return fmt.Errorf("cannot create directory: %w", err)
	}
	return cfg.SaveTo(filePath
```

2022-10-19 08:23 UTC, bboozzoo commented on cmd/wick/helpers.go
> +		return fmt.Errorf("invalid serializer: serailizer must be json, msgpack or cbor")
to be consistent with the rest of the errors:
```suggestion
		return fmt.Errorf("invalid serializer: serailizer must be 'json', 'msgpack' or 'cbor'")
```

2022-10-19 08:23 UTC, bboozzoo commented on cmd/wick/helpers.go
> +		return fmt.Errorf("invalid realm: realm must contain no space")
```suggestion
		return fmt.Errorf("invalid realm: realm is unset or contains whitespace")
```

2022-10-19 08:23 UTC, bboozzoo commented on cmd/wick/helpers.go
> +	if len(s) != 64 && len(s) != 32 {
I would suggest actually doing `hex.DecodeString()` and then validating the key length

2022-10-19 08:25 UTC, zyga commented
> It is expected that this PR is in a branch with a JIRA PLT-328 which thoroughly describes the change.

Public repositories should not use internal jira tickets where all the details are locked away. It would be best to bring that information to the pull request itself (ideally to git history)

2022-10-19 08:42 UTC, zyga reviewed
Quick review of a codebase I'm not very familiar with.

I have one extra remark that applies to all the errors. It's really
easy write errors that can be both meaningful for humans (because they produce nice error messages) and also fully typed and easy to match.

This avoids both repetitive error pattern of `fmt.Errorf("foobar error: blah %s", ...)` and allows one to make adjustments to the overall look and feel of individual messages more easily:

``` go
type DrinkError struct {
  Err error
}

func (e DrinkError) Error() {
   return fmt.Sprintf("drink error: %v", e.Err)
}

func (e DrinkError) Unwrap() error {
   return e.Err
}

var (
  ErrNoJuice = errors.New("not enough juice")
  ErrNoStraw = errors.New("straw is missing")
)
```

This lets you both use `errors.Is` to find root causes deeply as well as just print the errors.

I'm not sure if you want to adjust the code to use this style overall, but I find that a bit easier to work with than the hand-made `fmt.Errorf` style errors.

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +		return fmt.Errorf("invalid url : url must not be empty")
```suggestion
		return fmt.Errorf("invalid url: url must not be empty")
```

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +	case "ws", "rs", "tcp":
What does `rs` stand for?

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +	if s == "" || strings.Contains(s, " ") {
I don't know the correct values of wamp realms but is this sufficient validation? Is a realm `foo` correct? Is a realm `foo<non-breaking-space>` correct? I think this should be locked down, because it (as it stands now) accepts a lot of quirky strings.

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +			true, true, validateURL)
Nitpick, roll avoid boolean options, roll them into a struct and pass a struct with named fields instead.

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +		inputAuthrole, err := askForInput(reader, writer, "Enter authrole", "", false,
Nitpick: `Enter authentication role`.

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +		inputAuthMethod, err := askForInput(reader, writer, "Enter authmethod", "anonymous", true,
Nitpick `Enter authentication method`.

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +		inputAuthid, err := askForInput(reader, writer, "Enter authid", "", false,
What is `authid`? I'm asking to understand what this _should_ say to be a little bit more comprehensible (especially to people who have their first contact with wamp, like I do).

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +		inputTicket, err := askForInput(reader, writer, "Enter ticket", "", true,
Is there a validator for the ticket?

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +func ensureFile(filePath string) error {
I'm puzzled by the need to create an empty file. This should probably return an open file instead.

2022-10-19 08:42 UTC, zyga commented on cmd/wick/helpers.go
> +	signal.Notify(sigCh, os.Interrupt)
In case you _do_ I would strongly recommend `signal.NotifyContext` and pass the context around.

2022-10-19 08:58 UTC, bboozzoo commented on cmd/wick/helpers.go
> +	case "ws", "rs", "tcp":
Asked the same question. It's apparently something from autobahn, raw socket I'm told. Asked for `tcp` to be added, but `rs` was left behind as backward compatibility thing.

2022-10-19 12:19 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +	signal.Notify(sigCh, os.Interrupt)
removed

2022-10-19 12:20 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +		if err = os.MkdirAll(filepath.Dir(filePath), os.ModePerm); err != nil {
Done

2022-10-19 12:20 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +	err := ensureFile(filePath)
Worked Thanks

2022-10-19 12:20 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +		return fmt.Errorf("invalid serializer: serailizer must be json, msgpack or cbor")
Done

2022-10-19 12:21 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +	if len(s) != 64 && len(s) != 32 {
Done

2022-10-19 12:30 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +	if s == "" || strings.Contains(s, " ") {
have added more validations

2022-10-19 12:30 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +			true, true, validateURL)
Done

2022-10-19 12:30 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +		inputAuthrole, err := askForInput(reader, writer, "Enter authrole", "", false,
Done

2022-10-19 12:31 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +		inputAuthMethod, err := askForInput(reader, writer, "Enter authmethod", "anonymous", true,
Done

2022-10-19 12:35 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +func ensureFile(filePath string) error {
no longer needed. removed

2022-10-19 12:47 UTC, muzzammilshahid commented on cmd/wick/helpers.go
> +		inputAuthid, err := askForInput(reader, writer, "Enter authid", "", false,
authid is like username. I have changed it to bit more comprehensive

2022-10-21 12:25 UTC, om26er commented
We need a few changes in the behavior

1. wick configure (without --profile should automatically create a default profile)
2. the configure wizard should ask for `authid` even if we are not using any authentication (probably a prompt change)
3. The configure wizard is using the wrong word `Enter authentication role:` as that's alien to WAMP. We use authid and authrole even in the spec. But more importantly, the wizard should not save authrole at all since it is assigned by the router.
4. The "Enter authentication method:" prompt should be "Enter authmethod" similar to what we have in the CLI but more importantly what people conventionally use in different WAMP libraries (and spec). It should also suggest the support methods upfront in the prompt

2022-10-21 12:26 UTC, om26er commented
Also the profile that we are creating contains unneeded variables as well. I created a profile for anonymous auth but it contains keys for different authmethods, albeit empty
```
[default]
url         = ws://localhost:8080/ws
realm       = realm1
serializer  = msgpack
authid      = anonymous
authrole    = yo
authmethod  = anonymous
private-key = 
ticket      = 
secret      =
```

2022-10-21 12:27 UTC, om26er requested changes
see comments

2022-10-21 13:46 UTC, bboozzoo commented on cmd/wick/helpers.go
> +	var realmPattern = regexp.MustCompile(`^([0-9a-z_]+\.)*([0-9a-z_]+)$`)
don't our realms generated by default include `-` and `.` as well?

2022-10-21 13:46 UTC, bboozzoo commented on cmd/wick/helpers.go
> +		// line is empty but default is provided returns it
```suggestion
		// line is empty but a default is provided, so use it
```

2022-10-21 13:46 UTC, bboozzoo commented on cmd/wick/helpers.go
> +				resultErr = fmt.Errorf("default value is not provided but input is empty")
```suggestion
				resultErr = fmt.Errorf(no input and no default value")
```

2022-10-21 13:46 UTC, bboozzoo commented on cmd/wick/helpers.go
> +				fmt.Fprintf(writer, "Failed to validate input string: %s\n", err)
```suggestion
				fmt.Fprintf(writer, "Invalid input: %v\n", err)
```

2022-10-21 14:25 UTC, om26er commented on cmd/wick/helpers.go
> +	var realmPattern = regexp.MustCompile(`^([0-9a-z_]+\.)*([0-9a-z_]+)$`)
Instead of cooking a custom regex, we should be able use some of the helpers that Nexus already has. @muzzammilshahid Please look into `wamp.URI.ValidURI()` https://github.com/gammazero/nexus/blob/3b7d4f25dbc7b9655bbbc22faf6ba66bade7fa8f/wamp/identifier.go#L36 but we can do that in a follow up branch

2022-10-21 14:32 UTC, merged