add ephemeral procedure
s-things/wick pull request #59
Opened 2022-05-23 14:37 UTC by shahidghafoor00

2022-05-24 00:47 UTC, om26er requested changes

2022-05-24 00:47 UTC, om26er commented on cmd/wick/main.go
> +	invokeCount       = register.Flag("invoke-count", "Invoke session after its called N times").Int()
The text should read something like "leave session after it's called requested times"

2022-05-24 00:47 UTC, om26er commented on wamp/main.go
> +	var isInvokeEnabled = false
we need a better name for that variable. `hasMaxInvokeCount`

2022-05-24 00:47 UTC, om26er commented on wamp/main.go
> +		*&isInvokeEnabled = true
No need for `*&`

2022-05-24 00:47 UTC, om26er commented on wamp/main.go
> +		if isInvokeEnabled {
This code block should executed at the end of this function not at the start

2022-05-24 00:47 UTC, om26er commented on wamp/main.go
> +				os.Exit(1)
exit code 1 means that the program exited with an error. The error code here should be 0, which means the program exited without an error.

2022-05-24 00:47 UTC, om26er commented on wamp/main.go
> +				os.Exit(1)
Also I am not sure if you need to exit the session manually if you already called `session.Done()`

2022-05-24 10:13 UTC, shahidghafoor00 commented on wamp/main.go
> +				os.Exit(1)
`session.Done()` didn’t exited out so I manually exited out.

2022-05-25 19:44 UTC, om26er requested changes

2022-05-25 19:44 UTC, om26er commented on wamp/main.go
> +	hasMaxInvokeCount := false
This code block can be simplified as
```
hasMaxInvokeCount := invokeCount > 0
```

2022-05-25 19:44 UTC, om26er commented on wamp/main.go
> +			if invokeCount == 0 {
once the invoke count is reached, we should just call session.Unregister(), that will ensure no other client is able to call that procedure again. Doing that essentially reduces the hacks in our logic

2022-05-25 19:44 UTC, om26er commented on wamp/main.go
> +					logger.Println("after time called")
these logs can be removed, not needed

2022-05-25 20:15 UTC, om26er commented
LGTM

2022-05-25 20:15 UTC, merged